apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      student: geher-marcell

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jedligram-backend-deployment
spec:
  selector:
    matchLabels:
      app: jedligram-backend
  template:
    metadata:
      labels:
        app: jedligram-backend
    spec:
      containers:
        - name: jedligram-backend
          image: ghcr.io/geher-marcell/jedligram-backend-vizsgaremek:${IMAGE_TAG}

          ports:
            - containerPort: 8000

          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/html/storage/app/public

          env:
            - name: APP_URL
              value: "https://jedligrambackend-gehermarcell.jcloud.jedlik.cloud"
            - name: APP_NAME
              value: "Jedligram Backend"
            - name: APP_ENV
              value: "local"
            - name: APP_DEBUG
              value: "true"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_USERNAME
              value: "geher.marcell"
            - name: DB_HOST
              value: "jcloud02.jedlik.eu"
            - name: DB_DATABASE
              value: "geher_marcell_db_1"
            - name: DB_PORT
              value: "3306"
            - name: APP_KEY
              value: "${APP_KEY}"
            - name: SESSION_DRIVER
              value: "file"
            - name: CACHE_STORE
              value: "file"
            - name: LOG_CHANNEL
              value: "stderr"
            - name: SCOUT_DRIVER
              value: "database"
            - name: SYSADMIN_USERNAME
              value: "admin"
            - name: SYSADMIN_PASSWORD
              value: "${SYSADMIN_PASSWORD}"
            - name: API_VERSION
              value: "${IMAGE_TAG}"
            # - name: LDAP_CACHE
            #   value: "false"
            # - name: LDAP_LOGGING
            #   value: "false"
            # - name: LDAP_CONNECTION
            #   value: "default"
            # - name: LDAP_HOST
            #   value: "jdc.jedlik.eu"
            # - name: LDAP_USERNAME
            #   value: "cn=Vendég,ou=Idegen,dc=jedlik,dc=helyi"
            # - name: LDAP_PASSWORD
            #   value: "${LDAP_PASSWORD}"
            # - name: LDAP_PORT
            #   value: "389"
            # - name: LDAP_BASE_DN
            #   value: "dc=jedlik,dc=helyi"
            # - name: LDAP_TIMEOUT
            #   value: "5"
            # - name: LDAP_SSL
            #   value: "false"
            # - name: LDAP_TLS
            #   value: "false"
            # - name: LDAP_SASL
            #   value: "false"
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/www/html/storage"]
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/html/storage/app/public

---
apiVersion: v1
kind: Service
metadata:
  name: jedligram-backend-cluster-ip-service
spec:
  selector:
    app: jedligram-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jedligram-certificate
spec:
  secretName: jedligram-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - jedligrambackend-gehermarcell.jcloud.jedlik.cloud

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jedligram-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jedligrambackend-gehermarcell.jcloud.jedlik.cloud
      secretName: jedligram-certificate

  rules:
    - host: jedligrambackend-gehermarcell.jcloud.jedlik.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jedligram-backend-cluster-ip-service
                port:
                  number: 80
