apiVersion: apps/v1
kind: Deployment
metadata:
  name: jedligram-backend-deployment
spec:
  selector:
    matchLabels:
      app: jedligram-backend
  template:
    metadata:
      labels:
        app: jedligram-backend
    spec:
      containers:
        - name: jedligram-backend
          image: ghcr.io/${{ REPO_OWNER }}/jedligram-backend-vizsgaremek:${IMAGE_TAG}

          ports:
            - containerPort: 8000
          env:
            - name: APP_URL
              value: "http://jedligrambackend-gehermarcell.jcloud.jedlik.cloud"
            - name: APP_NAME
              value: "Jedligram Backend"
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_USERNAME
              value: "geher.marcell"
            - name: DB_HOST
              value: "jcloud02.jedlik.eu"
            - name: DB_DATABASE
              value: "geher_marcell_db_1"
            - name: DB_PORT
              value: "3306"
            - name: APP_KEY
              value: "${APP_KEY}"
            - name: SESSION_DRIVER
              value: "file"
            - name: CACHE_STORE
              value: "file"
            - name: LOG_CHANNEL
              value: "stderr"
            - name: SCOUT_DRIVER
              value: "database"
            # - name: LDAP_CACHE
            #   value: "false"
            # - name: LDAP_LOGGING
            #   value: "false"
            # - name: LDAP_CONNECTION
            #   value: "default"
            # - name: LDAP_HOST
            #   value: "jdc.jedlik.eu"
            # - name: LDAP_USERNAME
            #   value: "cn=Vendég,ou=Idegen,dc=jedlik,dc=helyi"
            # - name: LDAP_PASSWORD
            #   value: "${LDAP_PASSWORD}"
            # - name: LDAP_PORT
            #   value: "389"
            # - name: LDAP_BASE_DN
            #   value: "dc=jedlik,dc=helyi"
            # - name: LDAP_TIMEOUT
            #   value: "5"
            # - name: LDAP_SSL
            #   value: "false"
            # - name: LDAP_TLS
            #   value: "false"
            # - name: LDAP_SASL
            #   value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: jedligram-backend-cluster-ip-service
spec:
  selector:
    app: jedligram-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jedligram-backend-ingress
spec:
  ingressClassName: nginx

  rules:
    - host: jedligrambackend-gehermarcell.jcloud.jedlik.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jedligram-backend-cluster-ip-service
                port:
                  number: 80
