### Variables
@baseUrl = http://127.0.0.1:8000/api
@email = test@example.com
@password = password123

### 1. Register a new user
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
    "name": "Test User",
    "email": "{{email}}",
    "password": "{{password}}",
    "password_confirmation": "{{password}}"
}

### 2. Login (Run this to get your Token)
# @name loginRequest
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### 3. Logout
# We use the token from the request above automatically
POST {{baseUrl}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}


###
GET {{baseUrl}}/threads
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

POST {{baseUrl}}/threads
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

{
    "name": "Old Thread Title 3",
    "description": "This is the content of the new thread."
}

###

GET {{baseUrl}}/threads/search?search=old
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###
GET {{baseUrl}}/threads/1
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

POST {{baseUrl}}/threads/1/join
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

DELETE {{baseUrl}}/threads/1/leave
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

GET {{baseUrl}}/threads/1/posts
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

POST {{baseUrl}}/threads/1/post
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

{
    "content": "pisztiposzti"
}

###

GET  {{baseUrl}}/posts
Content-Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

GET  {{baseUrl}}/posts/11
Content-Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

GET {{baseUrl}}/users/search?search=Ho
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

GET {{baseUrl}}/users/3
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###

GET {{baseUrl}}/users/1/threads
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

###
PUT {{baseUrl}}/users/5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}

{
    "name": "Updated Name",
    "email": "updated_email@exampl1e.com"
}

# TODO: prettier error message when trying to update a nonexistent user

###

POST {{baseUrl}}/posts/1/vote
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.access_token}}
Accept: application/json

{
    "is_upvote": true
}


