name: Deploy to JedlikCloud

on:
  push:
    branches:
      - github-deploy-action # Change this if your main branch is called 'master'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Keep your specific PHP version
          extensions: fileinfo
          tools: composer

      - name: Create .env file from Secrets
        shell: pwsh
        # Pass the secrets as environment variables to the step
        env:
          ENV_FILE_CONTENT: ${{ secrets.LARAVEL_ENV_FILE }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          # Read from the environment variable instead of injecting directly into the code
          $env:ENV_FILE_CONTENT | Out-File -FilePath ".env" -Encoding utf8
          
          # Append FTP credentials to the bottom
          Add-Content -Path ".env" -Value "FTP_USER=$env:FTP_USER"
          Add-Content -Path ".env" -Value "FTP_PASS=$env:FTP_PASS"

      - name: Run Deployment Batch Script
        shell: cmd
        # Pass the FTP credentials as environment variables for the .ps1 script
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          echo "Starting deployment script..."
          call deploy.bat 
