name: Build Docker Image, Push to GHCR, and Deploy to Kubernetes

on:
  push:
    branches:
      - master
      - improve-cicd
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      #      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #      APP_KEY: ${{ secrets.APP_KEY }}
      IMAGE_TAG: ${{ github.sha }}
      #      SYSADMIN_PASSWORD: ${{ secrets.SYSADMIN_PASSWORD }}
      #      LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Geher-Marcell
          password: ${{ secrets.PACKAGE_RW_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/geher-marcell/jedligram-backend-vizsgaremek:latest, ghcr.io/geher-marcell/jedligram-backend-vizsgaremek:${{ github.sha }}
          file: ./Dockerfile

      - uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
      - name: Deploy with env substitution
        run: |
          kubectl apply -f -
          kubectl rollout restart deployment jedligram-backend-deployment
